url: http://joaopedronardari.github.com
baseurl:

# Site settings
title: João Pedro Nardari
email: joaonardari@gmail.com
description: "Paulistano de 21 anos apaixonado por tecnologia, ama música, adora desafios e sonha um dia viajar o mundo. Atualmente está cursando Sistemas de Informação na USP. É desenvolvedor de aplicativos (Android e IOS) e sistemas Web."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff9900
  secondary: ff6600  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: João Pedro Nardari
  pic: 1
  position: Developer
  social:
    - title: linkedin
      url: https://br.linkedin.com/in/joaonardari
    - title: github
      url: https://github.com/joaopedronardari
    - title: android
      url: https://play.google.com/store/apps/dev?id=7777993588034533433
